version: 2
updates:
  - package-ecosystem: "npm" # or pip, maven, gradle, composer, github-actions
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    rebase-strategy: "auto"
    labels:
      - "deps"
      - "security"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "deps"
      - "actions"